TICKERS = [
    "AA", "AAL", "AAPL", "ABBV", "ABNB", "ABR", "ACB", "ACHR", "ADBE", "ADI",
    "AEO", "AFRM", "AG", "AGNC", "AI", "ALAB", "AMAT", "AMD", "AMZN", "ANET",
    "ANF", "APA", "APLD", "APP", "ARKG", "ARKK", "ARM", "ASHR", "ASML", "ASTS",
    "AUR", "AVGO", "AZN", "BA", "BABA", "BAC", "BB", "BBAI", "BBWI", "BHC",
    "BIDU", "BILI", "BITO", "BITX", "BMBL", "BMY", "BOIL", "BP", "BTDR", "BTU",
    "C", "CAVA", "CCJ", "CCL", "CE", "CEG", "CELH", "CHWY", "CIFR", "CLF",
    "CLS", "CLSK", "CMCSA", "CMG", "COIN", "CORZ", "COST", "CPNG", "CPRI", "CRM",
    "CRSP", "CRWD", "CSCO", "CVNA", "CVS", "CVX", "CZR", "DAL", "DASH", "DBX",
    "DDOG", "DECK", "DELL", "DG", "DIA", "DIS", "DJT", "DKNG", "DLTR", "DOW",
    "DVN", "EBAY", "EEM", "EFA", "EL", "ELF", "ENPH", "ENVX", "EQT", "ET",
    "ETSY", "EWZ", "F", "FCX", "FSLR", "FTNT", "FUTU", "FXI", "GAP", "GDX",
    "GDXJ", "GEV", "GILD", "GLD", "GLW", "GM", "GME", "GOLD", "GOOG", "GOOGL",
    "GS", "HAL", "HD", "HE", "HIMS", "HL", "HLF", "HOOD", "HPE", "HPQ",
    "HUT", "HYG", "IBIT", "IBM", "IEF", "INTC", "IONQ", "IREN", "IWM", "IYR",
    "JBLU", "JD", "JETS", "JNJ", "JOBY", "JPM", "KEY", "KHC", "KMI", "KO",
    "KOLD", "KR", "KRE", "KSS", "KVUE", "KWEB", "LAZR", "LI", "LLY", "LMND",
    "LQD", "LRCX", "LULU", "LUNR", "LUV", "LVS", "LYFT", "M", "MARA", "MBLY",
    "MCD", "MCHP", "MDB", "MDT", "META", "MGM", "MMM", "MO", "MOS", "MRK",
    "MRNA", "MRVL", "MS", "MSFT", "MSTR", "MSTU", "MSTX", "MTCH", "MU", "NBIS",
    "NCLH", "NEE", "NEM", "NET", "NFLX", "NKE", "NLY", "NU", "NVAX", "NVDA",
    "NVDL", "NVO", "OKLO", "OKTA", "ON", "ONON", "ORCL", "OXY", "PANW",
    "PARA", "PATH", "PBR", "PCG", "PDD", "PENN", "PEP", "PFE", "PG", "PINS",
    "PLTR", "PTON", "PYPL", "QBTS", "QCOM", "QQQ", "QS", "QUBT", "RBLX", "RCAT",
    "RCL", "RDDT", "RDFN", "RGTI", "RIOT", "RIVN", "RKLB", "ROKU", "RTX", "RUN",
    "RXRX", "SBUX", "SCHW", "SEDG", "SERV", "SHOP", "SIRI", "SLB", "SLV",
    "SMCI", "SMH", "SMR", "SNAP", "SNOW", "SOFI", "SOUN", "SOXL", "SOXS",
    "SPXS", "SPY", "SQQQ", "T", "TBT", "TDOC", "TECK", "TEM", "TEVA", "TFC",
    "TGT", "TIGR", "TJX", "TLT", "TMF", "TNA", "TOST", "TQQQ", "TSLA", "TSLL",
    "TSM", "TTD", "TTWO", "TWLO", "TXN", "TZA", "U", "UAL", "UBER", "UNG",
    "UNH", "UPS", "UPST", "USB", "USO", "UVIX", "UVXY", "V", "VALE", "VKTX",
    "VRT", "VST", "VXX", "VZ", "W", "WBA", "WBD", "WDC", "WFC", "WMT", "WOLF",
    "WYNN", "X", "XBI", "XLE", "XLF", "XLI", "XLU", "XLV", "XOM", "XOP", "XP",
    "XPEV", "XYZ", "YINN", "Z", "ZETA", "ZIM", "ZM", "ZS"
]

# I scraped tickers that have good options liquidity and are over $5.
